# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'EstudoiOs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EstudoiOs
  pod 'Alamofire', '4.8.0'
  pod 'SwiftyJSON'

  target 'EstudoiOsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EstudoiOsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
